### PR TITLE
Disable unalign_double_arrow rule from Symfony preset

### PR DESCRIPTION
**Pull request by sagikazarmark**
@joelwurtz IIRC you wanted this.

Would make sense here: https://styleci.io/analyses/XkAZAz

### CODE REVIEW

**Comment by dbu** [comment]
i am confused by the number of negations :-)

i am -1 on aligning the arrows - whatever that means for this PR

**Comment by sagikazarmark** [comment]
Symfony preset by default DOES NOT align the arrows, this is what unalign means. Disabling this would remove this fixer.

@dbu is it a personal taste or you have an explanation too? (It doesn't make it worse or better, but if you have a logical path you followed, I would be happy to hear)

**Comment by joelwurtz** [comment]
+1 for this, would love to force alignement but another PR i guess (here we don't force anything so it's free to user)

**Comment by joelwurtz** [comment]
There is also the unalign of equal to remove i guess, but also another PR imo.

**Comment by dbu** [comment]
my reason is that the alignment needs to unnecessary changes and is
cumbersome when editing files, as you need to change indention of
unrelated stuff. for phpdoc i can live with that because readability is
crucial. in the code i don't find it that hard to read.

but if you are all in favor, its no big drama. but we indeed should
force one or the other, not leave it ignored.

and why not handle the other alignment rule in the same PR? its pretty
much the same topic to me, and would be weird to not be consistent
between the two.

**Comment by sagikazarmark** [comment]
Maintenance is also one of my reasons against. In case of big arrays, it is quite hard maintain. StyleCI can fix it, but I am reluctant to merge PRs for every little spacing issue with a separate commit (actually two, merge commit also counts), instead of just fixing and amending (in case of a feature branch of course).

An other is complexity: in case of multi-dimensional arrays, how would you align? Align the same levels? Align all levels to the same position? In this case, maintenance is even harder.

Also, I don't like aligning in YAML files, I don't like aligning in case of multiple variable set (equals), so why double arrow then?

It's kind of a -0.5 from me.

**Comment by joelwurtz** [comment]
Really don't mind overall but i like to align everywhere i can, many times code also serve as a documentation. 

+1 for me, for aligning everywhere.

My main concern is to have consistence (so align everywhere or unalign everywhere, but not something between that).

**Comment by sagikazarmark** [comment]
If we are talking about aligning everywhere, then it's a -1 from me.

**Comment by joelwurtz** [comment]
So let's keep unalign everywhere like Symfony does

**Pull request closed without merging**
