### PR TITLE
Add a php cs file

### PR DESCRIPTION
**Pull request by joelwurtz**
Proposal for a cs file see #1 and #2 

We all have our habits, way of doing thing, etc... IMO having a common style for code is necessary, however choice of rules should not take forever. Then i want to propose the following workflow for choosing coding rules : 

1) Every contributor can propose a rule in a new issue / pull request
2) Every contributor should do a vote about the rule: +1 / 0 (don't give a fuck) / -1
3) After 1 week on the proposed rule, vote are counted, and if it's win by majority (50% + 1), rule is added / removed to the cs file

(A contributor in this case is someone who belongs to the organisation)

This is mainly to avoid useless debate for something which is highly subjective.

This cs file include all psr1 and psr2 rules as the base coding style.

If workflow is agreed by everyone, i will propose some other rules.

### CODE REVIEW

**Comment by dbu** [comment]
i agree we should have a common code style and find your proposal fine.
i would be happy to stick with the symfony CS and not create exceptions
for whitespace (more to avoid discussion than because of a strong opinion)

+1 for the short array syntax (its what we do already) and the ordered
`use` statements.

what about using the styleci service? the upshot is that this can be
integrated into the pull requests here on github, and their service can
even provide a patch / do a pull request against the branch with the cs
fixes that can be done automatically.

**Comment by sagikazarmark** [comment]
+1 from me for both the workflow and the proposal.

I was also thinking about styleci, but I am not as impressed now as I was when I found it. What can Style CI do that Scrutinizer doesn't? Also, it seems creating CIs is the hype nowadays.

https://houndci.com/

That said, if you think it worth and gives us something more than Scrutinizer, then I would happily set it up. For example I am not sure if Scrutinizer breaks the build or automatically opens a PR.

**Comment by dbu** [comment]
styleci is convenient because we would not need to change the travis
build at all, its a completely separate integration and only about cs.
scrutinizer is about coverage and such afaik, less about cs.

**Comment by sagikazarmark** [comment]
Ok, convinced me.

**Comment by joelwurtz** [comment]
> +1 for the short array syntax (its what we do already) and the ordered
> `use` statements.

Sorry @dbu i have remove those rules / proposal and also the symfony one, as i don't want to introduce new rules here (2 different purposes) and just want to agree on a operation workflow for the moment.

(I will add these in another issue)

**Comment by sagikazarmark** [comment]
Cool, let's go ahead then.

**Comment by shulard** [comment]
Hello !
Do you plan to add the php-cs-fixer dependency to composer or do you think it's better to require a global installation on developer computer ?

**Comment by sagikazarmark** [comment]
I think it is better kept out of the composer dependencies.

**Comment by dbu** [comment]
> Do you plan to add the php-cs-fixer dependency to composer or do you
> think it's better to require a global installation on developer computer ?

the idea is to commit it in each of the repositories. there would even
be a script that we could adapt to sync the files that must be the same
into all our repos:
https://github.com/dantleech/cmf-utils/blob/master/scripts/sync_styleci

**Pull request merged**
