### PR TITLE
Enhancement: Require at least PHP 7.1

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] requires at least PHP 7.1

### CODE REVIEW

**Review by dbu — APPROVED** [review]
@php-http/owners do you agree with me and @localheinz that new repos we create will only support php 7.1 or better?

**Comment by localheinz** [comment]
@dbu

Is there anything I can do to help move forward?

**Review by xabbuh — APPROVED** [review]

**Comment by dbu** [comment]
thanks!

**Comment by localheinz** [comment]
Thank you, @dbu and @xabbuh!

**Pull request merged**
