### PR TITLE
use pretty-ci instead of style-ci

### PR DESCRIPTION
**Pull request by dbu**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | as per https://github.com/php-http/HttplugBundle/pull/278
| Documentation   | -
| License         | MIT

#### What's in this PR?

Remove configuration for the styleci php-cs-fixer bridge and move config into php-cs-fixer

#### Why?

The bridge is abandoned. styleci seems to not offer anything to run codestyle locally with the same configuration as their service. pretty-ci runs exactly php-cs-fixer as a service.

### CODE REVIEW

**Comment by dbu** [comment]
not strictly related, but while cleaning up: we have a .scrutinizer.yml file in many of our repositories, but did not enable scrutinizer (checked on httplug and HttplugBundle). is it okay if i remove that file?

**Comment by xabbuh** [comment]
What about enabling Scrutinizer CI instead?

**Comment by GrahamCampbell** [comment]
👎 On this. I genuinely believe removing the local dev cs fixing tools is the right way to go, and just leave it to CI to handle. No php-cs-fixer config or dependencies should be in any codebase.

**Comment by dbu** [comment]
i don't care much either way, as long as its cleanly set up.

i like the simplicity of styleci, but in the discussions leading to https://github.com/php-http/HttplugBundle/pull/278 people said they really care about being able to run the cs fixer locally. (the thing was triggered by us using an abandoned package that allowed to use the styleci configuration locally with the php-cs-fixer)
@php-http/owners can you please tell how you feel about this?

**Comment by sagikazarmark** [comment]
Scrutinizer catches a hole lot of issues that CS fixer does not, provides code coverage info, etc, so I would leave it as an option here. Turning it on is rather simple, I think everyone should have access to the php-http organization on scrutinizer, but ping me if that's not the case.

About pretty ci vs style ci: I really don't care much, but I like the idea that we can use the same config for local execution, so I probably lean towards pretty ci.

@GrahamCampbell I disagree, I really hate to push amendment commits with messages like "Fix CS" and wait for another turn of CI (not necessarily the one executing CS scans, I know StyleCI is blazing fast, but test running is not necessarily). So I like to execute style checks locally before pushing or even commiting. But it's fine, this is rather a personal preference thing as such providing flexibility should be the priority here. I don't have to use phpcs locally even if there is a config, but I can't use it if there is no config.

**Comment by dbu** [comment]
right, we use scrutinizer in some repositories, and this is just the template. i won't touch that then. (the PR does not change it, it was just a question i asked out of confusion ;-) )

so, shall we merge this change and shall i switch the other php-http repos to pretty-ci? as i see so far, graham is :-1: on this and me and mark are :+1: ?

**Review by Nyholm — APPROVED** [review]

**Pull request merged**
