### PR TITLE
Disable PHPDoc order fixer

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by dbu** [comment]
+1

should we add a comment in the config file explaining that styleci wants a weird order and this is why we disable the check?

**Comment by sagikazarmark** [comment]
Better now?

**Comment by dbu** [comment]
:+1:

**Comment by sagikazarmark** [comment]
Reverted this as it turned out misconfiguration caused the problem.

**Comment by mekras** [comment]
It's not a wired order. You can see in phpDocumentor examples: http://phpdoc.org/docs/latest/references/phpdoc/tags/throws.html.

**Comment by dbu** [comment]
hm, indeed. still feels the wrong order to me. imho the expected flow of
param - return should come before the error flow.

**Comment by sagikazarmark** [comment]
I reverted it as it turned out the reorder happened because of misconfiguration: by default there is no configuration in the repo. In that case the default preset is "recommended", which contained that fixer. As soon as I added symfony preset, the problem disappeared.

**Pull request merged**
